//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface IClient {
    /**
     * @return Success
     */
    getAstronautDutiesByName(name: string): Observable<GetAstronautDutiesByNameResult>;
    /**
     * @param body (optional) 
     * @return Success
     */
    createAstronautDuty(body: CreateAstronautDuty | undefined): Observable<CreateAstronautDutyResult>;
    /**
     * @param body (optional) 
     * @return Success
     */
    updateAstronautDuty(id: number, body: UpdateAstronautDuty | undefined): Observable<BaseResponse>;
    /**
     * @return Success
     */
    getAllPeople(): Observable<GetPeopleResult>;
    /**
     * @return Success
     */
    getPersonByName(name: string): Observable<GetPersonByNameResult>;
    /**
     * @param body (optional) 
     * @return Success
     */
    createPerson(body: string | undefined): Observable<BaseResponse>;
    /**
     * @param body (optional) 
     * @return Success
     */
    updatePerson(currentName: string, body: string | undefined): Observable<UpdatePersonResult>;
}

@Injectable()
export class Client implements IClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return Success
     */
    getAstronautDutiesByName(name: string): Observable<GetAstronautDutiesByNameResult> {
        let url_ = this.baseUrl + "/AstronautDuty/{name}";
        if (name === undefined || name === null)
            throw new globalThis.Error("The parameter 'name' must be defined.");
        url_ = url_.replace("{name}", encodeURIComponent("" + name));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAstronautDutiesByName(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAstronautDutiesByName(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetAstronautDutiesByNameResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetAstronautDutiesByNameResult>;
        }));
    }

    protected processGetAstronautDutiesByName(response: HttpResponseBase): Observable<GetAstronautDutiesByNameResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetAstronautDutiesByNameResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = BaseResponse.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = BaseResponse.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createAstronautDuty(body: CreateAstronautDuty | undefined): Observable<CreateAstronautDutyResult> {
        let url_ = this.baseUrl + "/AstronautDuty";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateAstronautDuty(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateAstronautDuty(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CreateAstronautDutyResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CreateAstronautDutyResult>;
        }));
    }

    protected processCreateAstronautDuty(response: HttpResponseBase): Observable<CreateAstronautDutyResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CreateAstronautDutyResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BaseResponse.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = BaseResponse.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateAstronautDuty(id: number, body: UpdateAstronautDuty | undefined): Observable<BaseResponse> {
        let url_ = this.baseUrl + "/AstronautDuty/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateAstronautDuty(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateAstronautDuty(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BaseResponse>;
        }));
    }

    protected processUpdateAstronautDuty(response: HttpResponseBase): Observable<BaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BaseResponse.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = BaseResponse.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return Success
     */
    getAllPeople(): Observable<GetPeopleResult> {
        let url_ = this.baseUrl + "/Person/all";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAllPeople(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAllPeople(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetPeopleResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetPeopleResult>;
        }));
    }

    protected processGetAllPeople(response: HttpResponseBase): Observable<GetPeopleResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetPeopleResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = BaseResponse.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return Success
     */
    getPersonByName(name: string): Observable<GetPersonByNameResult> {
        let url_ = this.baseUrl + "/Person/{name}";
        if (name === undefined || name === null)
            throw new globalThis.Error("The parameter 'name' must be defined.");
        url_ = url_.replace("{name}", encodeURIComponent("" + name));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPersonByName(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPersonByName(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetPersonByNameResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetPersonByNameResult>;
        }));
    }

    protected processGetPersonByName(response: HttpResponseBase): Observable<GetPersonByNameResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetPersonByNameResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = BaseResponse.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = BaseResponse.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createPerson(body: string | undefined): Observable<BaseResponse> {
        let url_ = this.baseUrl + "/Person";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreatePerson(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreatePerson(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BaseResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BaseResponse>;
        }));
    }

    protected processCreatePerson(response: HttpResponseBase): Observable<BaseResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = BaseResponse.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = BaseResponse.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updatePerson(currentName: string, body: string | undefined): Observable<UpdatePersonResult> {
        let url_ = this.baseUrl + "/Person/{currentName}";
        if (currentName === undefined || currentName === null)
            throw new globalThis.Error("The parameter 'currentName' must be defined.");
        url_ = url_.replace("{currentName}", encodeURIComponent("" + currentName));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdatePerson(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdatePerson(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<UpdatePersonResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<UpdatePersonResult>;
        }));
    }

    protected processUpdatePerson(response: HttpResponseBase): Observable<UpdatePersonResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UpdatePersonResult.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = BaseResponse.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = BaseResponse.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = BaseResponse.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export class AstronautDutyDto implements IAstronautDutyDto {
    id?: number;
    personId?: number;
    rank?: string | undefined;
    dutyTitle?: string | undefined;
    dutyStartDate?: Date;
    dutyEndDate?: Date | undefined;

    constructor(data?: IAstronautDutyDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.personId = _data["personId"];
            this.rank = _data["rank"];
            this.dutyTitle = _data["dutyTitle"];
            this.dutyStartDate = _data["dutyStartDate"] ? new Date(_data["dutyStartDate"].toString()) : undefined as any;
            this.dutyEndDate = _data["dutyEndDate"] ? new Date(_data["dutyEndDate"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): AstronautDutyDto {
        data = typeof data === 'object' ? data : {};
        let result = new AstronautDutyDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["personId"] = this.personId;
        data["rank"] = this.rank;
        data["dutyTitle"] = this.dutyTitle;
        data["dutyStartDate"] = this.dutyStartDate ? this.dutyStartDate.toISOString() : undefined as any;
        data["dutyEndDate"] = this.dutyEndDate ? this.dutyEndDate.toISOString() : undefined as any;
        return data;
    }
}

export interface IAstronautDutyDto {
    id?: number;
    personId?: number;
    rank?: string | undefined;
    dutyTitle?: string | undefined;
    dutyStartDate?: Date;
    dutyEndDate?: Date | undefined;
}

export class BaseResponse implements IBaseResponse {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;

    constructor(data?: IBaseResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.responseCode = _data["responseCode"];
        }
    }

    static fromJS(data: any): BaseResponse {
        data = typeof data === 'object' ? data : {};
        let result = new BaseResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["responseCode"] = this.responseCode;
        return data;
    }
}

export interface IBaseResponse {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
}

export class CreateAstronautDuty implements ICreateAstronautDuty {
    name?: string | undefined;
    rank?: string | undefined;
    dutyTitle?: string | undefined;
    dutyStartDate?: Date;

    constructor(data?: ICreateAstronautDuty) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.rank = _data["rank"];
            this.dutyTitle = _data["dutyTitle"];
            this.dutyStartDate = _data["dutyStartDate"] ? new Date(_data["dutyStartDate"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): CreateAstronautDuty {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAstronautDuty();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["rank"] = this.rank;
        data["dutyTitle"] = this.dutyTitle;
        data["dutyStartDate"] = this.dutyStartDate ? this.dutyStartDate.toISOString() : undefined as any;
        return data;
    }
}

export interface ICreateAstronautDuty {
    name?: string | undefined;
    rank?: string | undefined;
    dutyTitle?: string | undefined;
    dutyStartDate?: Date;
}

export class CreateAstronautDutyResult implements ICreateAstronautDutyResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    id?: number | undefined;

    constructor(data?: ICreateAstronautDutyResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.responseCode = _data["responseCode"];
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): CreateAstronautDutyResult {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAstronautDutyResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["responseCode"] = this.responseCode;
        data["id"] = this.id;
        return data;
    }
}

export interface ICreateAstronautDutyResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    id?: number | undefined;
}

export class GetAstronautDutiesByNameResult implements IGetAstronautDutiesByNameResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    person?: PersonAstronaut;
    astronautDuties?: AstronautDutyDto[] | undefined;

    constructor(data?: IGetAstronautDutiesByNameResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.responseCode = _data["responseCode"];
            this.person = _data["person"] ? PersonAstronaut.fromJS(_data["person"]) : undefined as any;
            if (Array.isArray(_data["astronautDuties"])) {
                this.astronautDuties = [] as any;
                for (let item of _data["astronautDuties"])
                    this.astronautDuties!.push(AstronautDutyDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetAstronautDutiesByNameResult {
        data = typeof data === 'object' ? data : {};
        let result = new GetAstronautDutiesByNameResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["responseCode"] = this.responseCode;
        data["person"] = this.person ? this.person.toJSON() : undefined as any;
        if (Array.isArray(this.astronautDuties)) {
            data["astronautDuties"] = [];
            for (let item of this.astronautDuties)
                data["astronautDuties"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IGetAstronautDutiesByNameResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    person?: PersonAstronaut;
    astronautDuties?: AstronautDutyDto[] | undefined;
}

export class GetPeopleResult implements IGetPeopleResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    people?: PersonAstronaut[] | undefined;

    constructor(data?: IGetPeopleResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.responseCode = _data["responseCode"];
            if (Array.isArray(_data["people"])) {
                this.people = [] as any;
                for (let item of _data["people"])
                    this.people!.push(PersonAstronaut.fromJS(item));
            }
        }
    }

    static fromJS(data: any): GetPeopleResult {
        data = typeof data === 'object' ? data : {};
        let result = new GetPeopleResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["responseCode"] = this.responseCode;
        if (Array.isArray(this.people)) {
            data["people"] = [];
            for (let item of this.people)
                data["people"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IGetPeopleResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    people?: PersonAstronaut[] | undefined;
}

export class GetPersonByNameResult implements IGetPersonByNameResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    person?: PersonAstronaut;

    constructor(data?: IGetPersonByNameResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.responseCode = _data["responseCode"];
            this.person = _data["person"] ? PersonAstronaut.fromJS(_data["person"]) : undefined as any;
        }
    }

    static fromJS(data: any): GetPersonByNameResult {
        data = typeof data === 'object' ? data : {};
        let result = new GetPersonByNameResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["responseCode"] = this.responseCode;
        data["person"] = this.person ? this.person.toJSON() : undefined as any;
        return data;
    }
}

export interface IGetPersonByNameResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    person?: PersonAstronaut;
}

export class PersonAstronaut implements IPersonAstronaut {
    personId?: number;
    name?: string | undefined;
    currentRank?: string | undefined;
    currentDutyTitle?: string | undefined;
    careerStartDate?: Date | undefined;
    careerEndDate?: Date | undefined;

    constructor(data?: IPersonAstronaut) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.personId = _data["personId"];
            this.name = _data["name"];
            this.currentRank = _data["currentRank"];
            this.currentDutyTitle = _data["currentDutyTitle"];
            this.careerStartDate = _data["careerStartDate"] ? new Date(_data["careerStartDate"].toString()) : undefined as any;
            this.careerEndDate = _data["careerEndDate"] ? new Date(_data["careerEndDate"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): PersonAstronaut {
        data = typeof data === 'object' ? data : {};
        let result = new PersonAstronaut();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["personId"] = this.personId;
        data["name"] = this.name;
        data["currentRank"] = this.currentRank;
        data["currentDutyTitle"] = this.currentDutyTitle;
        data["careerStartDate"] = this.careerStartDate ? this.careerStartDate.toISOString() : undefined as any;
        data["careerEndDate"] = this.careerEndDate ? this.careerEndDate.toISOString() : undefined as any;
        return data;
    }
}

export interface IPersonAstronaut {
    personId?: number;
    name?: string | undefined;
    currentRank?: string | undefined;
    currentDutyTitle?: string | undefined;
    careerStartDate?: Date | undefined;
    careerEndDate?: Date | undefined;
}

export class UpdateAstronautDuty implements IUpdateAstronautDuty {
    id?: number;
    rank?: string | undefined;
    dutyTitle?: string | undefined;
    dutyStartDate?: Date;
    dutyEndDate?: Date | undefined;

    constructor(data?: IUpdateAstronautDuty) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.rank = _data["rank"];
            this.dutyTitle = _data["dutyTitle"];
            this.dutyStartDate = _data["dutyStartDate"] ? new Date(_data["dutyStartDate"].toString()) : undefined as any;
            this.dutyEndDate = _data["dutyEndDate"] ? new Date(_data["dutyEndDate"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): UpdateAstronautDuty {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateAstronautDuty();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["rank"] = this.rank;
        data["dutyTitle"] = this.dutyTitle;
        data["dutyStartDate"] = this.dutyStartDate ? this.dutyStartDate.toISOString() : undefined as any;
        data["dutyEndDate"] = this.dutyEndDate ? this.dutyEndDate.toISOString() : undefined as any;
        return data;
    }
}

export interface IUpdateAstronautDuty {
    id?: number;
    rank?: string | undefined;
    dutyTitle?: string | undefined;
    dutyStartDate?: Date;
    dutyEndDate?: Date | undefined;
}

export class UpdatePersonResult implements IUpdatePersonResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    id?: number;
    newName?: string | undefined;

    constructor(data?: IUpdatePersonResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.message = _data["message"];
            this.responseCode = _data["responseCode"];
            this.id = _data["id"];
            this.newName = _data["newName"];
        }
    }

    static fromJS(data: any): UpdatePersonResult {
        data = typeof data === 'object' ? data : {};
        let result = new UpdatePersonResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["message"] = this.message;
        data["responseCode"] = this.responseCode;
        data["id"] = this.id;
        data["newName"] = this.newName;
        return data;
    }
}

export interface IUpdatePersonResult {
    success?: boolean;
    message?: string | undefined;
    responseCode?: number;
    id?: number;
    newName?: string | undefined;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}